services:
  vaultwarden:
    image: "${IMAGE}"
    container_name: "vaultwarden"
    restart: "always"
    networks:
      - "reverse-proxy"
    expose:
      - "80"
    volumes:
      - "./data/:/data/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.home.tastic`)"
      - "diun.enable=true"
      - "diun.include_tags=^1\\.\\d+\\.\\d+$"
      - "homepage.group=Network & Security"
      - "homepage.name=Vaultwarden"
      - "homepage.icon=vaultwarden.png"
      - "homepage.href=https://vault.home.tastic"
      - "homepage.description=Password Manager"

networks:
  reverse-proxy:
    external: true
